spring:
  datasource:
    url: jdbc:mysql://spring-boot-db.c6wukdjxvf6m.ap-northeast-2.rds.amazonaws.com:3306/myselectshop?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


